language: cpp

#
# Define the build matrix
#
env:
  global:
    - app_id=pvr.sledovanitv.cz

matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          update: true
          packages:
            - gcc-7
            - g++-7
      compiler: gcc
      script:
        - CC=gcc-7 CXX=g++-7 make
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          update: true
          packages:
            - gcc-7
            - g++-7
      compiler: clang
    - os: osx

#
# The addon source is automatically checked out in $TRAVIS_BUILD_DIR,
# we'll put the Kodi source on the same level
#
before_script:
  - cd $TRAVIS_BUILD_DIR/..
  - git clone --depth=1 https://github.com/xbmc/xbmc.git
  - cd ${app_id} && mkdir build && cd build
  - mkdir -p definition/${app_id}
  - echo ${app_id} $TRAVIS_BUILD_DIR $TRAVIS_COMMIT > definition/${app_id}/${app_id}.txt
  - if [ "$TRAVIS_OS_NAME" = osx ]; then export OPENSSL_ROOT_DIR='/usr/local/opt/openssl'; fi
  - cmake -DADDONS_TO_BUILD=${app_id} -DADDON_SRC_PREFIX=$TRAVIS_BUILD_DIR/.. -DADDONS_DEFINITION_DIR=$TRAVIS_BUILD_DIR/build/definition -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/../xbmc/addons -DPACKAGE_ZIP=1 $TRAVIS_BUILD_DIR/../xbmc/cmake/addons

script: make
